name: daobao
description: Homepage DAO

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter

  # State Management
  provider: ^6.0.1
  flutter_bloc: ^8.0.0

  # utilities
  auto_route: ^3.1.3
  freezed_annotation:
  flutter_web3: ^2.2.0-pre.6
  injectable: ^1.5.0
  get_it: ^7.2.0
  extended_masked_text: ^2.3.1
  json_annotation: ^4.3.0
  dio: ^4.0.4

  # ui
  responsive_framework: ^0.1.5
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  simple_animations: ^4.0.1
  iconly: ^1.0.1
  markdown_editable_textinput: ^2.0.2
  zefyrka: ^1.0.10
  markdown_widget: ^1.2.7
  cached_network_image: ^3.1.0+1
  lottie: ^1.2.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  injectable_generator:
  freezed:
  json_serializable:
  auto_route_generator: ^3.1.0

flutter:
  uses-material-design: false

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo/
