name: daobao
description: Homepage DAO

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter

  # State Management
  provider: ^6.0.1

  # utilities
  auto_route: ^3.1.3
  freezed_annotation:
  flutter_web3: ^2.2.0-pre.6

  # ui
  responsive_framework: ^0.1.5
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  simple_animations: ^4.0.1
  iconly: ^1.0.1
  markdown_editable_textinput: ^2.0.2
  zefyrka: ^1.0.10
  markdown_widget: ^1.2.7

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  freezed:
  auto_route_generator: ^3.1.0

flutter:
  uses-material-design: false

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo/
