name: Deploy to Firebase Hosting
"on": workflow_dispatch
jobs:
  build:
    # if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: actions/checkout@v2
      - run: flutter pub get
      - run: ' flutter build web -t "lib/main.dart" '
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOMEPAGEDAO }}"
          projectId: homepagedao
          channelId: live
